src/communicate/main.py
=> added b_set_forum_nick for issue #6

.github/workflows/deploy_archive_notifications.yml
changed python to 3.10 and other modules params.
=> convert GCF acrhive_notifications into python 3.10

src/communicate/main.py
=> Fix btn index; move search_follow_mode callback processing

src/communicate/main.py
This is temp version of possibility to on/off whitelist mode of following searches. Just because I didn't get to how to append new button for this possibility.
=> Manage search_follow_mode by text

src/communicate/main.py
The block is indented right under the else: #of if username=='AnatolyK1975' and get_search_follow_mode(cur, user_id)
=> Don't show button to on when the mode is on already

.vscode/settings.json, src/communicate/main.py
Previous PR made changes to vscode/settings.json.
This PR's goal is to undo that changes and to synchronize code from la_searcher_bot.
=> Undo previous canceled PR

src/api_get_active_searches/main.py, src/archive_notifications/main.py, src/archive_to_bigquery/main.py, src/check_first_posts_for_changes/main.py, src/compose_notifications/main.py, src/connect_to_forum/main.py, src/identify_updates_of_first_posts/main.py, src/identify_updates_of_topics/main.py, src/manage_topics/main.py, src/send_notifications_helper/main.py, src/send_notifications_helper_2/main.py, src/title_recognize/main.py, src/user_provide_info/main.py
=> remove spaces in all files

pyproject.toml, src/archive_to_bigquery/requirements.txt, uv.lock
=> fixes #550 - bigquery deploy

src/_dependencies/misc.py, src/api_get_active_searches/main.py, src/compose_notifications/main.py, src/identify_updates_of_first_posts/main.py, src/identify_updates_of_topics/main.py, src/manage_topics/main.py, src/send_notifications/main.py, src/send_notifications_helper/main.py, src/send_notifications_helper_2/main.py, src/user_provide_info/main.py, tests/dependencies/__init__.py, tests/dependencies/test_misc.py, tests/smoke/test_compose_notifications_generated.py, tests/smoke/test_identify_updates_of_first_posts_generated.py, tests/smoke/test_identify_updates_of_topics_generated.py, tests/smoke/test_manage_topics_generated.py, tests/smoke/test_send_notifications_generated.py, tests/smoke/test_send_notifications_helper_2_generated.py, tests/smoke/test_send_notifications_helper_generated.py, tests/test_api_get_active_searches.py, tests/tools/find_duplicates.py
#555
merge evaluate_city_locations
merge save_sending_status_to_notif_by_user
merge send_location_to_api
merge get_change_log_update_time
merge generate_random_function_id
=> 555 common code part 3

src/_dependencies/misc.py, src/compose_notifications/main.py, src/send_notifications/main.py, src/send_notifications_helper/main.py, src/send_notifications_helper_2/main.py, tests/smoke/test_compose_notifications_generated.py, tests/smoke/test_send_notifications_generated.py, tests/smoke/test_send_notifications_helper_2_generated.py, tests/smoke/test_send_notifications_helper_generated.py, tests/tools/find_duplicates.py
#555 
merge get_triggering_function
=> 555-common-code-part-5

src/_dependencies/content.py, src/api_get_active_searches/main.py, src/check_topics_by_upd_time/main.py, src/connect_to_forum/main.py, src/identify_updates_of_first_posts/main.py, src/user_provide_info/main.py, tests/dependencies/test_content.py, tests/smoke/test_connect_to_forum_generated.py, tests/test_run_bot.py, tests/tools/find_duplicates.py
#555
refact connect_to_forum
merge clean_up_content
=> 555 common code part 6

src/_dependencies/commons.py, src/_dependencies/misc.py, src/compose_notifications/main.py, src/connect_to_forum/main.py, src/identify_updates_of_topics/main.py, src/send_notifications/main.py, src/send_notifications_helper/main.py, src/send_notifications_helper_2/main.py, src/title_recognize/main.py, tests/common.py, tests/smoke/test_send_notifications_generated.py, tests/smoke/test_send_notifications_helper_2_generated.py, tests/smoke/test_send_notifications_helper_generated.py, tests/tools/find_duplicates.py
#555
merge send_message_to_api, process_response
identify_updates_of_topics dataclass
=> 555 common code part 7

src/_dependencies/cloud_func_parallel_guard.py, src/compose_notifications/main.py, src/send_notifications/main.py, src/send_notifications_helper/main.py, src/send_notifications_helper_2/main.py, tests/dependencies/test_db_guard.py
#555
merge:
check_if_other_functions_are_working,
record_start_of_function,
record_finish_of_function
=> 555-common-code-part-8

src/_dependencies/cloud_func_parallel_guard.py, src/communicate/main.py, src/compose_notifications/main.py, src/identify_updates_of_topics/main.py, src/send_notifications/main.py, src/send_notifications_helper/main.py, src/send_notifications_helper_2/main.py, tests/common.py, tests/dependencies/test_db_guard.py, tests/smoke/test_compose_notifications_generated.py, tests/smoke/test_send_notifications_generated.py, tests/smoke/test_send_notifications_helper_2_generated.py, tests/smoke/test_send_notifications_helper_generated.py, tests/tools/find_duplicates.py
#555
merge check_and_save_event_id
SearchSummary -> dataclass
=> 555 common code part 9

src/connect_to_forum/main.py
=> fix error while saving cokies: read-only filesystem

src/compose_notifications/_utils/notifications_maker.py
=> fix: each new record was "doubled" for user because mailing_id already existed in moment of check

pyproject.toml, src/_dependencies/commons.py, src/_dependencies/content.py, src/compose_notifications/_utils/commons.py, src/compose_notifications/_utils/log_record_composer.py, src/compose_notifications/_utils/message_composer.py, src/compose_notifications/_utils/notifications_maker.py, src/compose_notifications/_utils/users_list_composer.py, src/identify_updates_of_first_posts/main.py, tests/factories/db_factories.py, tests/smoke/test_identify_updates_of_first_posts_generated.py, tests/test_compose_notifications/conftest.py, tests/test_compose_notifications/factories.py, tests/test_compose_notifications/test_change_log.py, tests/test_compose_notifications/test_message_composer.py, tests/test_compose_notifications/test_notification_maker.py, tests/test_compose_notifications/test_users_list_composer.py, tests/test_identify_updates_of_first_posts.py
- write tests
- decompose long functions for readability
- use common enum  "ChangeType"
- remove unused functions
=> Refact "identify_updates_of_first_posts"

pyproject.toml, src/_dependencies/cloud_func_parallel_guard.py, src/compose_notifications/_utils/notifications_maker.py, src/compose_notifications/_utils/users_list_composer.py, src/compose_notifications/main.py, src/connect_to_forum/main.py, src/identify_updates_of_first_posts/main.py, src/send_notifications/main.py, tests/test_connect_to_forum.py
now all defs should be typed for better checking with mypy
=> disallow untyped defs in mypy

tests/conftest.py, tests/dependencies/test_misc.py
=> speed up tests by disabling pubsub emulation

pyproject.toml, src/check_topics_by_upd_time/main.py, src/check_topics_by_upd_time/requirements.txt, src/identify_updates_of_folders/main.py, tests/fixtures/forum_main.html, tests/smoke/test_check_topics_by_upd_time_generated.py, tests/test_check_topics_by_upd_time.py, tests/test_identify_updates_of_folders.py, tests/tools/run_check_topics_by_upd_time.py, tests/tools/run_identify_updates_of_folders.py, uv.lock
add threading to identify_updates_of_folders;
add local run with local file storage, emulating cloud storage; 
add retry for http requests; 
cache session;
add tests;
refactor identify_updates_of_folders and check_topics_by_upd_time; 
save upd time in cloud storage to avoid useless checks; 
add type checking.
=> forum improve folders update

src/check_topics_by_upd_time/main.py, tests/test_check_topics_by_upd_time.py
send to pubsub only changed folders
=> fix shapshots check

pyproject.toml, src/api_get_active_searches/main.py, tests/factories/db_factories.py, tests/smoke/test_api_get_active_searches_generated.py, tests/test_api_get_active_searches.py
add tests;
add mypy;
fix failed tests.
=> refact api_get_active_searches:

README.md, pyproject.toml, src/user_provide_info/main.py, tests/conftest.py, tests/factories/db_factories.py, tests/test_compose_notifications/conftest.py, tests/test_identify_updates_of_topics.py, tests/test_user_provide_info.py
add tests;
add pydantic schema for responses;
add mypy checking.
=> Refact user provide info

src/compose_notifications/_utils/users_list_composer.py, tests/test_compose_notifications/test_users_list_composer.py
=> fix SQL iin _filter_users_not_following_this_search

src/title_recognize/main.py
to see request and response in logs
=> add logging to title_recognize

pyproject.toml, src/manage_users/main.py, tests/factories/db_factories.py, tests/test_manage_users.py
add tests;
refactor code;
pydantic for input data.
=> refactoring of function "manage_users"

src/_dependencies/misc.py, src/send_notifications/main.py
closes #639
change log_level from INFO to DEBUG for some useless messages when sending notifications
=> reduce log level for useless messages

pyproject.toml, src/manage_topics/main.py, tests/test_manage_topics.py
=> Refact manage topics

src/send_notifications/main.py, tests/test_send_notifications.py
If you do not limit the re-sending of unsuccessful messages, they will be sent indefinitely, overloading the queue.
https://t.me/c/1546571473/5042/7102
=> retry sending failed messages over 5 minutes at least

.github/workflows/deploy_send_debug_to_admin.yml
=> new deploy try 2

.github/workflows/deploy_archive_notifications.yml, .github/workflows/deploy_archive_to_bigquery.yml, .github/workflows/deploy_check_first_posts_for_changes.yml, .github/workflows/deploy_check_topics_by_upd_time.yml, .github/workflows/deploy_communicate.yml, .github/workflows/deploy_compose_notifications.yml, .github/workflows/deploy_connect_to_forum.yml, .github/workflows/deploy_identify_updates_of_first_posts.yml, .github/workflows/deploy_identify_updates_of_topics.yml, .github/workflows/deploy_manage_topics.yml, .github/workflows/deploy_manage_users.yml, .github/workflows/deploy_send_debug_to_admin.yml, .github/workflows/deploy_send_notifications.yml, .github/workflows/deploy_users_activate.yml
#661 other workflows (without Gen2)
=> fix other workflows to use Artifacts Registry

pyproject.toml, src/_dependencies/commons.py, src/archive_notifications/main.py, src/archive_to_bigquery/main.py
`archive_to_bigquery`, `archive_notifications`.
Typehints, small refactoring.
=> Refact archive functions

src/_dependencies/misc.py
Fix error:
```
identify_updates_of_topics
io4p1sj9l148
TEMP - THIS BIG ERROR HAPPENED, forum_search_item=ForumSearchItem(title='Жива Женщина, 36 лет, СВАО, г. Москва', search_id=86717, replies_count=11, start_datetime=datetime.datetime(2025, 3, 14, 23, 28, 33, tzinfo=datetime.timezone.utc))
Traceback (most recent call last):
File "/layers/google.python.pip/pip/lib/python3.10/site-packages/requests/models.py", line 971, in json
return complexjson.loads(self.text, **kwargs)
File "/layers/google.python.runtime/python/lib/python3.10/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/layers/google.python.runtime/python/lib/python3.10/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File …
```
=> add retry for make_api_call

src/communicate/main.py, tests/test_user_provide_info.py
1. Searches that are not showed in active searches list should be excluded from following.
2. class SearchFollowingMode added to 'communicate' package
=> diff_searches_marked; class SearchFollowingMode

src/identify_updates_of_topics/_utils/external_api.py
Yandex returns coordinates in order "lon, lat".
=> fix coordinates order from yandex

pyproject.toml, src/check_first_posts_for_changes/_utils/commons.py, src/check_first_posts_for_changes/_utils/database.py, src/check_first_posts_for_changes/_utils/forum.py, src/check_first_posts_for_changes/main.py, src/identify_updates_of_topics/_utils/folder_updater.py, tests/fixtures/forum_viewtopic_first_post.html, tests/test_check_first_posts_for_changes.py
- move out nested functions;
- remove global vars;
- use dataclasses;
- add tests;
- fix mypy.
+ Fix logging in `identify_updates_of_topics`.
=> Refactoring `check_first_posts_for_changes`:

pyproject.toml, src/check_first_posts_for_changes/_utils/commons.py, src/check_first_posts_for_changes/_utils/database.py, src/check_first_posts_for_changes/_utils/forum.py, src/check_first_posts_for_changes/main.py, src/identify_updates_of_topics/_utils/folder_updater.py, tests/fixtures/forum_viewtopic_first_post.html, tests/test_check_first_posts_for_changes.py
Return back pr #673 reverted in #681 while forum was down
=> Refact check first posts for changes

src/check_first_posts_for_changes/_utils/forum.py, src/identify_updates_of_topics/_utils/forum.py
=> check "403 Forbidden" in response to detect unavailability of forum

pyproject.toml, src/_dependencies/cloud_func_parallel_guard.py, src/_dependencies/commons.py, src/_dependencies/content.py, src/_dependencies/misc.py, src/user_provide_info/main.py, tests/common.py, tests/dependencies/test_misc.py, tests/factories/db_factories.py, tests/factories/test_factories.py, tests/test_check_first_posts_for_changes.py, tests/test_communicate/test_main.py, tests/test_compose_notifications/factories.py, tests/test_compose_notifications/test_change_log.py, tests/test_compose_notifications/test_message_composer.py, tests/test_identify_updates_of_topics/factories.py, tests/test_send_notifications.py
add typehints for `_dependencies`;
add test communicate.main to correct coverage calculation; 
try to stabilize tests.
=> final typing steps

src/_dependencies/misc.py, src/compose_notifications/_utils/users_list_composer.py, src/connect_to_forum/main.py
replace unsafe `eval` with secure `ast.literal_eval`
=> remove the last raw `eval`

src/compose_notifications/_utils/users_list_composer.py, src/identify_updates_of_topics/_utils/folder_updater.py
1. Log user_ids in `compose_notifications` for initial users list.
2. Log change of folder in `identify_updates_of_topics`.
=> Extend logging.

src/_dependencies/telegram_api_wrapper.py
to mitigate timeouts / network errors / etc.. while sending messages
=> add retry for telegram queries

src/identify_updates_of_topics/_utils/forum.py, src/manage_users/main.py
add retry for forum parsing;
increase timeout to 30 seconds;
fix logging in manage_users
=> Fix timeout errors in parsing script

src/identify_updates_of_topics/_utils/database.py, src/identify_updates_of_topics/_utils/folder_updater.py, tests/test_title_recognize.py
https://lizaalert.org/forum/viewtopic.php?f=367&t=93575
Notification looks so:
We can consider forum folder. In this case, folder 367 contains only events.
=> Recognize topyc_type_id=10(event) by folder

docker-compose.yml, src/_dependencies/telegram_api_wrapper.py, src/communicate/_utils/buttons.py, src/communicate/_utils/common.py, src/communicate/_utils/database.py, src/communicate/_utils/decorators.py, src/communicate/_utils/handlers/button_handlers.py, src/communicate/_utils/handlers/callback_handlers.py, src/communicate/_utils/handlers/region_select_handlers.py, src/communicate/_utils/handlers/view_searches_handlers.py, src/communicate/_utils/regions.py, src/communicate/main.py
- move all geography functions in one class;
- split `_update_and_download_list_of_regions`;
- move region selection handlers to separate module;
- formalize `callback_data` with pydantic model;
- and make postgres db accessible only from localhost.
=> Change region selection to inline keyboard

src/_dependencies/commons.py, src/_dependencies/misc.py, src/_dependencies/pubsub.py, src/_dependencies/telegram_api_wrapper.py, src/archive_notifications/main.py, src/check_first_posts_for_changes/_utils/forum.py, src/check_first_posts_for_changes/main.py, src/check_topics_by_upd_time/main.py, src/communicate/_utils/common.py, src/communicate/_utils/handlers/state_handlers.py, src/communicate/main.py, src/compose_notifications/_utils/notifications_maker.py, src/compose_notifications/main.py, src/identify_updates_of_first_posts/main.py, src/identify_updates_of_topics/_utils/database.py, src/identify_updates_of_topics/_utils/forum.py, src/identify_updates_of_topics/main.py, src/manage_topics/main.py, src/manage_users/main.py, src/send_notifications/main.py, tests/common.py, tests/conftest.py, tests/test_check_first_posts_for_changes.py, tests/test_compose_notifications/conftest.py, tests/test_identify_updates_of_first_posts.py, tests/test_manage_users.py, tests/test_send_notifications.py, tests/tools/run_bot.py, tests/tools/run_check_topics_by_upd_time.py, tests/tools/run_identify_updates_of_topics.py
Split `publish_to_pubsub` to separate functions for each topic with formalized arguments.
=> refactor pub/sub calls

src/_dependencies/commons.py, src/_dependencies/misc.py, src/_dependencies/pubsub.py, src/_dependencies/telegram_api_wrapper.py, src/archive_notifications/main.py, src/check_first_posts_for_changes/_utils/forum.py, src/check_first_posts_for_changes/main.py, src/check_topics_by_upd_time/main.py, src/communicate/_utils/common.py, src/communicate/_utils/handlers/state_handlers.py, src/communicate/main.py, src/compose_notifications/_utils/notifications_maker.py, src/compose_notifications/main.py, src/identify_updates_of_first_posts/main.py, src/identify_updates_of_topics/_utils/database.py, src/identify_updates_of_topics/_utils/forum.py, src/identify_updates_of_topics/main.py, src/manage_topics/main.py, src/manage_users/main.py, src/send_notifications/main.py, tests/common.py, tests/conftest.py, tests/test_check_first_posts_for_changes.py, tests/test_compose_notifications/conftest.py, tests/test_identify_updates_of_first_posts.py, tests/test_manage_users.py, tests/test_send_notifications.py, tests/tools/run_bot.py, tests/tools/run_check_topics_by_upd_time.py, tests/tools/run_identify_updates_of_topics.py
This reverts commit ac213f505a5741a000fc070b11ab01b58f710886, reversing changes made to 6bb4832e028fda9f215e9a0afcef26f38e44055a.
=> Revert "Merge pull request #732 from cherrytea-dev/pubsub-args-v2"

src/_dependencies/commons.py, src/_dependencies/misc.py, src/_dependencies/pubsub.py, src/_dependencies/telegram_api_wrapper.py, src/archive_notifications/main.py, src/check_first_posts_for_changes/_utils/forum.py, src/check_first_posts_for_changes/main.py, src/check_topics_by_upd_time/main.py, src/communicate/_utils/common.py, src/communicate/_utils/handlers/state_handlers.py, src/communicate/main.py, src/compose_notifications/_utils/notifications_maker.py, src/compose_notifications/main.py, src/identify_updates_of_first_posts/main.py, src/identify_updates_of_topics/_utils/database.py, src/identify_updates_of_topics/_utils/forum.py, src/identify_updates_of_topics/main.py, src/manage_topics/main.py, src/manage_users/main.py, src/send_notifications/main.py, tests/common.py, tests/conftest.py, tests/test_check_first_posts_for_changes.py, tests/test_compose_notifications/conftest.py, tests/test_identify_updates_of_first_posts.py, tests/test_manage_users.py, tests/test_send_notifications.py, tests/tools/run_bot.py, tests/tools/run_check_topics_by_upd_time.py, tests/tools/run_identify_updates_of_topics.py
second attempt of #732 , which was reverted in #733
=> Pubsub args v3

pyproject.toml, src/check_topics_by_upd_time/main.py, src/identify_updates_of_topics/_utils/database.py, src/identify_updates_of_topics/_utils/folder_updater.py, tests/common.py, tests/factories/db_models.py, tests/test_check_topics_by_upd_time.py, tests/test_identify_updates_of_topics/test_db_client.py, tests/tools/db.sql, tests/tools/run_bot.py, tests/tools/run_check_topics_by_upd_time.py, tests/tools/run_identify_updates_of_topics.py, tests/tools/run_send_notifications.py, uv.lock
- add key-value storage to models;
- add db functions to work with key-value;
- add logging to local functions run scripts.
=> Use key-value storage in postgres instead of S3 buckets

src/_dependencies/commons.py, tests/dependencies/test_content.py
Fix: incorrect HTML after adding clickable phone links in some cases.
=> fix nested phone links in messages

src/title_recognize/_utils/recognizer.py, tests/test_title_recognize.py
simple guard against common spam messages in forum
=> dummy spam detector

src/_dependencies/content.py, src/check_first_posts_for_changes/_utils/forum.py, src/identify_updates_of_topics/_utils/forum.py
check for following text:
```
General Error  Return to index page     General Error SQL ERROR [ mysqli ]No such file or directory [2002]An sql error occurred while fetching this page. Please contact an administrator if this problem persists.      Powered by phpBB® Forum Software © phpBB Limited 
```
=> one more check for forum availability

src/title_recognize/_utils/recognizer.py
fix: detection by title, not by content
=> fix spam detection

src/check_first_posts_for_changes/_utils/forum.py
need to understand why does not working function "is_forum_unavailable"
=> add logging
